---

- name: Create docker registry local data directory
  file: path={{ docker_registry_local_data_dir }} state=directory

- name: Start docker registry
  docker_container:
    name:   "{{ docker_registry_container_name }}"
    image:  "registry:2"
    volumes: "{{ docker_registry_local_data_dir }}:/var/lib/registry"
    published_ports:  "{{ docker_registry_host_port }}:5000"
    restart_policy:   "on-failure"
    restart_retries:  5
    state:  started
